# Generated by Django 5.0.4 on 2024-04-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='gender',
        ),
    ]
